---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data(instacart)

instacart %>% 
filter(product_name == "Apples") %>% 
group_by(order_dow) %>% 
mutate(order_dow = as.factor(recode(order_dow, `0` = "Mon", `1` = "Tues", `2` = "Wed", `3` = "Thurs", `4` = "Fri", `5` = "Sat", `6` = "Sun"))) %>% 
summarize(n_apples = n()) %>% 
  plot_ly(
    x = ~order_dow, y = ~n_apples, color = ~order_dow,
    type = "bar"
  )

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>% 
  filter(user_id %in% 1:5000 & aisle == "ice cream ice") %>% 
  group_by(order_hour_of_day) %>% 
  summarize(n_ice_cream = n()) %>% 
  plot_ly(
    x = ~order_hour_of_day, y = ~n_ice_cream,
    type = "scatter"
  )

```

### Chart C

```{r}
instacart %>% 
  filter((department == "produce" | department == "snacks" | department == "household" | department == "beverages") & user_id %in% 1:200) %>% 
  plot_ly(
    x = ~department, y = ~order_hour_of_day, color = ~department,
    type = "box"
  )
```

